version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app/shared_sessions/:/tmp
      - ./app/src/veladero_digital/:/var/www/html
      - ./database:/var/lib/mysql
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
